# Generated by Django 6.0.4 on 2026-04-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Activos', '0001_initial'),
        ('Tecnico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_de_apertura', models.DateField(auto_created=True)),
                ('Codigo', models.IntegerField()),
                ('Fecha_de_cierra', models.DateField()),
                ('Tipo_de_intervencion', models.CharField(max_length=250)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Activo_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activos.activo')),
                ('Tecnico_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tecnico.trabajador')),
            ],
        ),
    ]
