# Generated by Django 6.0.4 on 2026-05-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervencion',
            old_name='Activo_asignado',
            new_name='ActivoAsignado',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='Fecha_de_apertura',
            new_name='FechaApertura',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='Fecha_de_cierra',
            new_name='FechaCierra',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='Tecnico_asignado',
            new_name='TecnicoAsignado',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='Tipo_de_intervencion',
            new_name='TipoIntervencion',
        ),
    ]
