# Generated by Django 6.0.4 on 2026-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidencias', '0002_rename_activo_asignado_intervencion_activoasignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='FechaApertura',
            field=models.DateField(),
        ),
    ]
