# Generated by Django 6.0.4 on 2026-05-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidencias', '0003_alter_intervencion_fechaapertura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervencion',
            old_name='FechaCierra',
            new_name='FechaCierre',
        ),
    ]
