# Generated by Django 6.0.4 on 2026-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_de_activacion', models.BooleanField(default=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Tipo_de_dispositivo', models.CharField(max_length=200)),
                ('Modelo', models.CharField(max_length=200)),
                ('Marca', models.CharField(max_length=100)),
                ('Fecha_instalacion', models.DateField(auto_now_add=True)),
                ('Ubicacion', models.CharField(max_length=200)),
                ('Estado_operativo', models.BooleanField(default=False)),
            ],
        ),
    ]
