# Generated by Django 6.0.4 on 2026-05-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='Codigo_de_activacion',
            new_name='CodigoActivacion',
        ),
        migrations.RenameField(
            model_name='activo',
            old_name='Estado_operativo',
            new_name='EstadoOperativo',
        ),
        migrations.RenameField(
            model_name='activo',
            old_name='Fecha_instalacion',
            new_name='FechaInstalacion',
        ),
        migrations.RenameField(
            model_name='activo',
            old_name='Tipo_de_dispositivo',
            new_name='TipoDispositivo',
        ),
    ]
