# Generated by Django 6.0.4 on 2026-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0002_rename_codigo_de_activacion_activo_codigoactivacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='CodigoActivacion',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='activo',
            name='FechaInstalacion',
            field=models.DateField(),
        ),
    ]
