# Generated by Django 6.0.4 on 2026-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=9)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
