# Generated by Django 6.0.4 on 2026-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='Telefono',
            field=models.IntegerField(max_length=15),
        ),
    ]
