# Generated by Django 6.0.4 on 2026-05-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tecnico', '0002_alter_trabajador_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='Telefono',
            field=models.IntegerField(),
        ),
    ]
