# Generated by Django 6.0.4 on 2026-05-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidencias', '0004_rename_fechacierra_intervencion_fechacierre'),
        ('Tecnico', '0003_alter_trabajador_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trabajador',
            new_name='Tecnico',
        ),
    ]
